name: Java CI

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        description: 'Name of artifact'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v3
        with:
          path: main
      
      - name: set-up-jdk-19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: checkout-cicd
        uses: actions/checkout@v3
        with:
          repository: remla23-team5/cicd
          path: cicd

      - name: build-with-maven
        run: |
          cd main
          mvn --batch-mode --update-snapshots -s ./../cicd/.github/workflows/maven.xml clean package -DskipTests
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: echo-artifact-name
        run: |
          echo "[ENV_VAR]: ${{ inputs.ARTIFACT_NAME }}"
          echo "if: ${{ github.event.inputs.ARTIFACT_NAME }}"
          echo "test: ${{ toJson(github.event) }}"
      
      - name: upload-artifact
        if: "${{ github.event.inputs.ARTIFACT_NAME != '' }}"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/artifact/
          if-no-files-found: error
