name: Java CI

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v3
        with:
          path: main
      
      - name: set-up-jdk-19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: checkout-cicd
        uses: actions/checkout@v3
        with:
          repository: remla23-team5/cicd
          path: cicd

      - name: echo
        run: |
          echo "[PWD]: $(pwd)"
          echo "[TREE]: $(tree)"
          echo "[LS]: $(ls -al)"


      - name: build-with-maven
        run: mvn --batch-mode --update-snapshots -s ./cicd/.github/workflows/maven.xml clean package -DskipTests
        env:
          USERNAME: ${{ env.GITHUB_ACTOR }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
