# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

on: 
  workflow_call:
    inputs:
      #   version:
      #     description: 'Semantic version of the Docker image'
      #     required: true
      #     type: string
      image_name:
        description: 'Name of the Docker image to build and publish'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=ref,event=branch

      - name: echo
        run: |
          echo "[outputs]: ${{ steps.meta.outputs }}"
          echo "[tags]: ${{ steps.meta.outputs.tags }}"
          echo "[labels]: ${{ steps.meta.outputs.labels }}"
          echo "[latest tag?]: git describe --abbrev=0 --tags"
          echo "[test other tag]: git describe --tags $(git rev-list --tags --max-count=1)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0 
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
