name: Create and publish a Docker image

on: 
  workflow_call:
    inputs:
      version:
        description: 'Semantic version of the Docker image'
        required: true
        type: string
      publish_latest:
        description: 'Also publish the image with the "latest" tag'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: echo
        run: |
          echo "[version]: ${{ inputs.version }}"
          echo "[version_tag]: v${{ inputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
           ${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.version }},
           ${{ env.REGISTRY }}/${{ github.repository }}:latest
          build-args: ${{ github.workspace }}/${{ github.repository }}
