name: Create and publish a Docker image

on: 
  workflow_call:
    inputs:
      version:
        description: 'Semantic version of the Docker image'
        required: true
        type: string
      image_name:
        description: 'Name of the Docker image to build and publish'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: echo
        run: |
          echo "[version]: ${{ inputs.version }}"
          echo "[version_tag]: v${{ inputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
           ${{ env.REGISTRY }}/${{ inputs.image_name }}:latest,
           ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.version }}
          buildArgs: ${{ github.workspace }}/${{ inputs.image_name}}
