name: Create and publish a Docker image

on: 
  workflow_call:
    inputs:
      IMAGE_NAME:
        description: 'Name of the Docker image to build and publish'
        required: true
        type: string
      ARTIFACT_NAME:
        description: 'Name of artifact'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
            #- name: tree
            #  run: |
            #    echo "[PWD]: $(pwd)"
            #    echo "[TREE]: $(tree)"
            #    cd ${{ github.workspace }}
            #    echo "[TREE]: $(tree -al)"

      - name: download-artifact
        if: inputs.IMAGE_NAME == 'remla23-team5/app'
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: java-ci/build
          workflow_conclusion: success
          name: app.jar
          repo: ${{ inputs.IMAGE_NAME }}
          if_no_artifact_found: fail

            # - name: download-artifact
            #   uses: actions/download-artifact@v2.1.1
            #   with:
            #     name: ${{ inputs.ARTIFACT_NAME }}
            #     path: ${{ github.workspace }}/app.jar

      - name: tree
        run: |
          echo "[PWD]: $(pwd)"
          echo "[TREE]: $(tree)"
          cd ${{ github.workspace }}
          echo "[TREE]: $(tree -al)"
      
      - name: SemVer
        run: |
          echo "[semver]: ${{ env.REGISTRY }}/${{ inputs.IMAGE_NAME }}:$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "GHCR_DOCKER_TAG=${{ env.REGISTRY }}/${{ inputs.IMAGE_NAME }}:$(git describe --tags $(git rev-list --tags --max-count=1))" >> "$GITHUB_ENV"
          echo "[env var]: ${{ env.GHCR_DOCKER_TAG }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ env.GHCR_DOCKER_TAG }}
          buildArgs: ${{ github.workspace }}/app.jar
