name: Tag and create new release

on:
  workflow_call:
    outputs:
      version: 
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: main branch update semantic version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
    
      - name: tag and create release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ steps.versioning.outputs.version_tag }}
          skipIfReleaseExists: true
