name: Increment version and create release

on:
  workflow_call:
    outputs:
      version_tag: 
        value: ${{ jobs.release.outputs.version_tag }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.versioning.outputs.version_tag }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --tags origin

      - name: update semantic version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          branch: test
          tag_prefix: "v"
          major_pattern: "breaking change:"
          minor_pattern: "feature:"
          version_format: "${major}.${minor}.${patch}"
    
      - name: tag and create release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.versioning.outputs.version_tag }}
          skipIfReleaseExists: true 
      