name: Semver Action
run-name: RunSemanticVersioning 

on:
  push:
    tags:
    - '*'
  workflow_call:

jobs:
  SemVer:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: force get git tag
        run: |
          git fetch --tags origin
          echo "[TAG]: $(git tag)"

      - name: semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "breaking change:"
          minor_pattern: "feature:"
          version_format: "${major}.${minor}.${patch}"
    
      - name: tag and create release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.versioning.outputs.version_tag }}
          skipIfReleaseExists: true 
      
