name: Tag and create snapshot release

on:
  workflow_call:
    outputs:
      version: 
        value: ${{ jobs.snapshot.outputs.previous_version }}-SNAPSHOT

jobs:
  snapshot:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.previous_version }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo repository
        run: |
          echo "${{ github.repository }}"
      
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: update semantic version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
    
      - name: feature branch semver
        id: snapshot
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.PAT_RELEASE }}
          tag: v${{ steps.versioning.outputs.previous_version }}-SNAPSHOT
          skipIfReleaseExists: false
          allowUpdates: true
          
