name: Tag and create snapshot release

on:
  workflow_call:
    outputs:
      version: 
        value: ${{ jobs.snapshot.outputs.version }}-SNAPSHOT

jobs:
  snapshot:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.previous_version }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"

      - name: Tag & Create snapshot release
        id: snapshot
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.PAT_RELEASE }}
          tag: v${{ steps.versioning.outputs.previous_version }}-SNAPSHOT
          skipIfReleaseExists: false
          allowUpdates: true
          
