name: Increment version and create release

on:
  push

jobs:
  snapshot:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: main branch update semantic version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "breaking change:"
          minor_pattern: "feature:"
          version_format: "${major}.${minor}.${patch}"
    
      - name: feature branch semver
        if: github.ref != 'refs/heads/main' && startsWith('snapshot:', ${{ github.event.head_commit.message }})
        id: snapshot
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.versioning.outputs.previous_version }}-SNAPSHOT
          skipIfReleaseExists: false
