name: Create tagged release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV
    
      - name: create normal release
        if: endsWith(github.event.base_ref, 'main') == true
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ env.version }}
          allowUpdates: false
          skipIfReleaseExists: true

      - name: create snapshot release
        if: endsWith(github.event.base_ref, 'main') == false
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ env.version }}-SNAPSHOT
          allowUpdates: true
          skipIfReleaseExists: false
